Merge Upstream
cc-tweaked/cc-restitched pull request #96
Opened 2022-05-02 21:41 UTC by Toad-Dev

Squid did some wizardry to make monitor rendering even faster, and made moving speaker sounds more fluid.

2022-05-05 08:50 UTC, SquidDev requested changes

2022-05-05 08:50 UTC, SquidDev commented on src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPosition.java
> +        public SpeakerPosition reify()
```suggestion
        @Environment( EnvType.CLIENT )
        public SpeakerPosition reify()
```

+imports above. See https://github.com/cc-tweaked/CC-Tweaked/commit/be45b718b32fb80f29e1e9ccba06a515bf3144b1.

Sorry, my fault!

2022-05-06 22:59 UTC, Merith-TK commented on src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPosition.java
> +        public SpeakerPosition reify()
should this change be made *before* I merge this? I was hoping there would be discussion on it before I merge this

2022-05-06 23:02 UTC, Toad-Dev commented on src/main/java/dan200/computercraft/shared/peripheral/speaker/SpeakerPosition.java
> +        public SpeakerPosition reify()
Yes, wait to merge. I will make the change in a few minutes!

2022-05-07 00:05 UTC, SquidDev approved these changes

2022-05-07 06:56 UTC, Merith-TK commented
safe to merge now?

2022-05-07 16:29 UTC, Toad-Dev commented
Yes, it's ready.

2022-05-07 21:23 UTC, merged